### PR TITLE
Complete rebuild of adapter code and new features added and New React UI

### PR DESCRIPTION
**Pull request by xXBJXx**
Hi Pix,
I have rebuilt the complete adapter code to TypeScript and worked out some issues. I have also rebuilt the admin UI completely in React.

Since the migration from the old config was unfortunately not possible, the old config is no longer compatible, when updating you should delete the adapter before and reinstall it, otherwise problems will occur.
Also, now the js-controller >=3.0.0 and admin >=5.3.3 is a requirement.

### CODE REVIEW

**Comment by Pix---** [comment]
Hello Issi, many thanks for contributing or even rebuilding this adapter in accordance to the new regulatiosn for adapters under the latest versions of admin and js-controller. I really appreciate your work.

**Comment by xXBJXx** [comment]
I use the adapter myself and saw that there were still some issues with feature request open and thought I'll rebuild the same to the latest state and install the things.
Have you ever thought about adding the adapter to the ioBroker community, then you can react faster to the problems?

**Comment by Pix---** [comment]
I think given the little time I can put into development that would be best. How do we proceed?

**Comment by xXBJXx** [comment]
here is a guide how to do it https://github.com/iobroker-community-adapters/info#how-to-become-a-member

**Comment by xXBJXx** [comment]
@Pix--- the conflicts should be fixed now

**Comment by xXBJXx** [comment]
@Apollon77 I've fixed all the conflicts you can look at the revised adapter and if everything fits merge and maybe add Sentry

**Pull request closed without merging**
