### PR TITLE
Pr/77

### PR DESCRIPTION
**Pull request by Pix---**

### CODE REVIEW

**Comment by Pix---** [comment]
Since I found some merge conflicts I am not able to merge your pr. Can u help?

**Comment by xXBJXx** [comment]
What conflicts are there? 
There may be many, since many files have deleted and new ones created.

**Comment by Pix---** [comment]
Just a Screenshot
screenshot

I am not able to solve this with github desktop. And xcode is not installed, so no command line ....

**Comment by xXBJXx** [comment]
Bluefox has tested something that was not there yesterday, but the gulpfile.js is not available in the new version because of the conflict.
If you like the changes and you don't have an application, you can also do a force push from your PC, that should overwrite everything on GitHub.

**Comment by xXBJXx** [comment]
you could try to revert yesterday's change in gulpfile.js i think bluefox just added a space that should work directly on GitHub

**Comment by klein0r** [comment]
Just delete the gulpfile and move to @iobroker/adapter-dev

https://github.com/ioBroker/create-adapter/blob/master/docs/updates/20211018_adapter-dev.md

**Comment by klein0r** [comment]
??

**Comment by xXBJXx** [comment]
I have released the new version so the PR is not necessary

**Pull request closed without merging**
